import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import react from 'eslint-plugin-react'
import eslintConfigPrettier from 'eslint-config-prettier'
import globals from 'globals'

/**
 * ESLint v9 flat config (migrated from the legacy .eslintrc.json).
 *
 * Uses the project's installed toolchain: @eslint/js, typescript-eslint,
 * eslint-plugin-react, and eslint-config-prettier. The legacy config also
 * referenced jsx-a11y / react-hooks / import / unused-imports plugins that are
 * no longer in package.json; their rules are intentionally omitted here. Re-add
 * those packages and rule blocks if that coverage is wanted again.
 *
 * Prettier is wired via eslint-config-prettier (which only turns off ESLint
 * rules that conflict with Prettier) rather than eslint-plugin-prettier, so
 * formatting is not enforced as lint errors. Run `prettier` separately if you
 * want to reformat — the codebase is not currently Prettier-formatted.
 */
export default tseslint.config(
  {
    // Replaces the legacy .eslintignore: build output and generated files.
    ignores: [
      'dist/',
      'build/',
      'coverage/',
      '.wrangler/',
      '.vercel/',
      'server/payload-types.ts', // auto-generated by `pnpm types:cms`
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,
  react.configs.flat.recommended,
  react.configs.flat['jsx-runtime'],

  {
    settings: { react: { version: 'detect' } },
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      'no-console': 'warn',
      'react/prop-types': 'off',
      'react/self-closing-comp': 'warn',
      // Apostrophes/quotes in JSX copy are intentional throughout the app.
      'react/no-unescaped-entities': 'warn',
      // Explicit `any` exists at a few SDK/generated-type boundaries; surface
      // it without blocking, matching the legacy config's warning-based stance.
      '@typescript-eslint/no-explicit-any': 'warn',
      // Allow the documented `interface FooSvgProps extends ComponentProps<'svg'> {}`
      // pattern (components/atoms/svgs) while still catching bare `{}` types.
      '@typescript-eslint/no-empty-object-type': ['error', { allowInterfaces: 'with-single-extends' }],
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          args: 'after-used',
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          ignoreRestSiblings: false,
        },
      ],
    },
  },

  // Must come last so it can disable formatting rules that conflict with Prettier.
  eslintConfigPrettier,
)
