/**
 * The Ladle build must carry a crawler refusal that reaches every URL.
 *
 * `design.wemeditate.com` was fully indexable (#174), and nothing in a test lane can see
 * that: the playground's `index.html` is generated by Ladle, so the refusal lives in two
 * static files that only the production build copies. This guard exercises the plugin that
 * copies them, so a renamed file or a moved directory fails here rather than in a deploy
 * nobody rechecks. `tests/smoke/ladle/` asserts the same two facts over HTTP.
 */
import { describe, it, expect } from 'vitest'
import { crawlerRefusal, readRefusalFile, REFUSAL_FILES } from '../../.ladle/crawler-refusal'

interface EmittedAsset {
  type: 'asset'
  fileName: string
  source: string
}

/** The assets the plugin writes into the build output, in one `generateBundle` pass. */
function emittedAssets(): EmittedAsset[] {
  const { generateBundle } = crawlerRefusal()

  if (typeof generateBundle !== 'function') {
    throw new Error('generateBundle must stay a plain function hook for this guard to call it')
  }

  const assets: EmittedAsset[] = []
  const context = { emitFile: (asset: EmittedAsset) => assets.push(asset) }

  generateBundle.call(context as never, {} as never, {} as never, { write: true } as never)

  return assets
}

describe('the Ladle crawler refusal', () => {
  it('emits every refusal file at the output root, unhashed', () => {
    const assets = emittedAssets()

    expect(assets.map((asset) => asset.fileName)).toEqual([...REFUSAL_FILES])

    for (const asset of assets) {
      expect(asset.type, `${asset.fileName} must be emitted as an asset`).toBe('asset')
      expect(asset.source.length, `${asset.fileName} must not be empty`).toBeGreaterThan(0)
    }
  })

  it('refuses every path in robots.txt', () => {
    const robots = readRefusalFile('robots.txt')

    // The directives, not the comments: a `Disallow` inside a comment refuses nothing.
    const directives = robots
      .split('\n')
      .filter((line) => line.trim() !== '' && !line.startsWith('#'))

    expect(directives).toContain('User-agent: *')
    expect(directives.indexOf('Disallow: /')).toBeGreaterThan(directives.indexOf('User-agent: *'))
  })

  it('sends noindex on every URL in _headers', () => {
    const headers = readRefusalFile('_headers')
    const rules = headers.split('\n').filter((line) => !line.startsWith('#'))

    // Cloudflare Pages reads an indented line as a header of the pattern above it, so the
    // two have to stay adjacent and in this order.
    const pattern = rules.findIndex((line) => line.trim() === '/*')

    expect(pattern, '_headers must hold a /* rule').toBeGreaterThanOrEqual(0)
    expect(rules[pattern + 1]).toMatch(/^\s+X-Robots-Tag:\s*noindex$/i)
  })
})
