/**
 * The `GET /api/atlas/seo` response shape (SahajCloud #645/#646, stage C3).
 *
 * ⚠ Hand-mirrored from SahajCloud's `src/endpoints/responseTypes.ts`.
 * `server/payload-types.ts` is generated by `pnpm types:cms`, and covers
 * collections only. A custom endpoint's response is not in it, so this
 * file must be maintained by hand. Re-read the upstream file when the
 * endpoint changes. The doc comments below record the contract points a
 * consumer must not guess at, because a wrong guess fails silently.
 */

/** One `<link rel="alternate" hreflang>` row. */
export interface AtlasSeoAlternate {
  hreflang: string
  href: string
}

/**
 * Open Graph properties keyed by their `property` attribute, so a caller
 * can emit them in a loop without knowing any of them by name.
 *
 * `og:site_name` is deliberately absent upstream. The host page already
 * knows what site it is. Every value is plain text and needs only
 * ordinary attribute escaping, which React does.
 */
export type AtlasSeoOpenGraph = Record<string, string>

/** One rung of the region ancestry, root first, ending at the page itself. */
export interface AtlasSeoBreadcrumb {
  name: string
  /** Atlas route, or `null` when a region in the chain has a blank slug. */
  route: string | null
  /** Canonical URL for that route, or `null` when one cannot be published. */
  url: string | null
}

/** A postal address, plus the one-line rendering most hosts display. */
export interface AtlasSeoAddress {
  venueName: string | null
  street: string | null
  room: string | null
  city: string | null
  region: string | null
  postCode: string | null
  country: string | null
  latitude: number | null
  longitude: number | null
  /** `street, room, city, region, country postCode` — blank parts dropped. */
  oneLine: string
}

/** When a class happens, in both renderable and machine-readable form. */
export interface AtlasSeoSchedule {
  /** e.g. `Every week on Saturday at 9:26 AM`. Empty when there is no schedule. */
  oneLine: string
  /** ISO 8601 instant of the first occurrence, `null` for a dormant class. */
  startDate: string | null
  /** ISO 8601 instant of the final occurrence's end, `null` when open-ended. */
  endDate: string | null
  /** IANA zone the wall-clock times are in. */
  timezone: string | null
  recurrence: 'DAILY' | 'WEEKLY' | 'MONTHLY' | null
  /** Two-letter recurrence weekdays (`MO`…`SU`). Empty unless weekly. */
  weekdays: string[]
  /** `HH:MM` local end time, when the class declares one. */
  endTime: string | null
  /** True for a class marked dormant — it has no active schedule. */
  inactive: boolean
}

/** An image, ready for `og:image` or an `<img>`. */
export interface AtlasSeoImage {
  url: string
  alt: string | null
}

/** One class in a region's listing. */
export interface AtlasSeoEventCard {
  id: number
  /** Atlas route for this class, e.g. `/gb/london/1204`. */
  route: string | null
  /** Canonical URL for that route, or `null` when one cannot be published. */
  url: string | null
  title: string
  /** One-line schedule, as in {@link AtlasSeoSchedule.oneLine}. */
  schedule: string
  /** One-line address. Empty for an online class. */
  address: string
  online: boolean
}

/** The body content of a class page. */
export interface AtlasSeoEventContent {
  title: string
  /** ISO 639-1 codes the class is conducted in. */
  languages: string[]
  schedule: AtlasSeoSchedule
  /** `null` for an online class. */
  address: AtlasSeoAddress | null
  onlineUrl: string | null
  website: string | null
  /**
   * The description as plain-text paragraphs, one per block.
   *
   * No HTML crosses this wire. Upstream converts Lexical to plain text, so
   * no consumer has to sanitize it. Render these as text. Never render
   * them with `dangerouslySetInnerHTML`.
   */
  paragraphs: string[]
  images: AtlasSeoImage[]
}

/** The body content of a region page. */
export interface AtlasSeoRegionContent {
  name: string
  subtitle: string | null
  level: 'country' | 'region' | 'city' | 'venue'
  /**
   * Classes in this region and every region beneath it, so a city's page
   * includes classes held at its shared venues. Capped upstream at 50.
   */
  events: AtlasSeoEventCard[]
  /** How many such classes exist in total. `events` may be capped below this. */
  eventCount: number
}

/** Fields every atlas SEO answer carries, whatever the route resolved to. */
interface AtlasSeoBase {
  /** The normalized route this answer describes — view segments dropped. */
  route: string
  /** The locale the answer was rendered for. */
  locale: string
  /** Page title, ready for `<title>`. */
  title: string
  /** Meta description — plain text, already length-bounded. `null` if none. */
  description: string | null
  /**
   * The canonical URL, byte-identical to the document's own `webUrl`, or
   * `null` when no owner can publish one.
   *
   * Locale-free by design. Nothing in the atlas is translated, so every
   * locale shares one canonical, and {@link alternates} differ only by the
   * widget's UI language. Never rebuild this logic: a second implementation
   * of the ownership walk is free to disagree with the first.
   */
  canonical: string | null
  /** hreflang rows: the enabled atlas locales plus `x-default`. Empty if no canonical. */
  alternates: AtlasSeoAlternate[]
  openGraph: AtlasSeoOpenGraph
  /**
   * A complete JSON-LD document, already serialized and escaped for direct
   * embedding in `<script type="application/ld+json">`.
   *
   * Emit it verbatim. Do not run it through `JSON.parse` or `stringify`,
   * and do not HTML-escape it again. Upstream's `jsonLdEscape()` already
   * neutralized `</script>` and `<!--`, with escapes that round-trip back
   * to the original characters.
   */
  jsonLd: string
  /** Region ancestry, root first, ending at this page. */
  breadcrumbs: AtlasSeoBreadcrumb[]
}

/**
 * `GET /api/atlas/seo` success body.
 *
 * A discriminated union on `type`. Narrowing once yields the content shape
 * for that variant, instead of an object where half the fields are `null`.
 */
export type AtlasSeoResponse =
  | (AtlasSeoBase & { type: 'region'; id: number; content: AtlasSeoRegionContent })
  | (AtlasSeoBase & { type: 'event'; id: number; content: AtlasSeoEventContent })
