/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectSlug".
 */
export type ProjectSlug = 'wemeditate-web' | 'wemeditate-app' | 'sahaj-atlas';
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RoleSlug".
 */
export type RoleSlug =
  | 'meditations-editor'
  | 'path-editor'
  | 'web-translator'
  | 'wemeditate-web-client'
  | 'wemeditate-app-client'
  | 'sahaj-atlas-client';

export interface Config {
  auth: {
    managers: ManagerAuthOperations;
    clients: ClientAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    meditations: Meditation;
    music: Music;
    albums: Album;
    lessons: Lesson;
    lectures: Lecture;
    frames: Frame;
    narrators: Narrator;
    authors: Author;
    images: Image;
    files: File;
    'image-tags': ImageTag;
    'meditation-tags': MeditationTag;
    'music-tags': MusicTag;
    'page-tags': PageTag;
    managers: Manager;
    clients: Client;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    albums: {
      music: 'music';
    };
    authors: {
      articles: 'pages';
    };
    'image-tags': {
      images: 'images';
    };
    'meditation-tags': {
      meditations: 'meditations';
    };
    'music-tags': {
      music: 'music';
    };
    'page-tags': {
      pages: 'pages';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    meditations: MeditationsSelect<false> | MeditationsSelect<true>;
    music: MusicSelect<false> | MusicSelect<true>;
    albums: AlbumsSelect<false> | AlbumsSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    lectures: LecturesSelect<false> | LecturesSelect<true>;
    frames: FramesSelect<false> | FramesSelect<true>;
    narrators: NarratorsSelect<false> | NarratorsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    images: ImagesSelect<false> | ImagesSelect<true>;
    files: FilesSelect<false> | FilesSelect<true>;
    'image-tags': ImageTagsSelect<false> | ImageTagsSelect<true>;
    'meditation-tags': MeditationTagsSelect<false> | MeditationTagsSelect<true>;
    'music-tags': MusicTagsSelect<false> | MusicTagsSelect<true>;
    'page-tags': PageTagsSelect<false> | PageTagsSelect<true>;
    managers: ManagersSelect<false> | ManagersSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'es' | 'de' | 'it' | 'fr' | 'ru' | 'ro' | 'cs' | 'uk' | 'el' | 'hy' | 'pl' | 'pt-br' | 'fa' | 'bg' | 'tr')
    | (
        | 'en'
        | 'es'
        | 'de'
        | 'it'
        | 'fr'
        | 'ru'
        | 'ro'
        | 'cs'
        | 'uk'
        | 'el'
        | 'hy'
        | 'pl'
        | 'pt-br'
        | 'fa'
        | 'bg'
        | 'tr'
      )[];
  globals: {
    'we-meditate-web-settings': WeMeditateWebSetting;
    'we-meditate-app-settings': WeMeditateAppSetting;
    'sahaj-atlas-settings': SahajAtlasSetting;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'we-meditate-web-settings': WeMeditateWebSettingsSelect<false> | WeMeditateWebSettingsSelect<true>;
    'we-meditate-app-settings': WeMeditateAppSettingsSelect<false> | WeMeditateAppSettingsSelect<true>;
    'sahaj-atlas-settings': SahajAtlasSettingsSelect<false> | SahajAtlasSettingsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale:
    | 'en'
    | 'es'
    | 'de'
    | 'it'
    | 'fr'
    | 'ru'
    | 'ro'
    | 'cs'
    | 'uk'
    | 'el'
    | 'hy'
    | 'pl'
    | 'pt-br'
    | 'fa'
    | 'bg'
    | 'tr';
  user:
    | (Manager & {
        collection: 'managers';
      })
    | (Client & {
        collection: 'clients';
      });
  jobs: {
    tasks: {
      resetClientUsage: TaskResetClientUsage;
      trackClientUsage: TaskTrackClientUsage;
      cleanupOrphanedMedia: TaskCleanupOrphanedMedia;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface ManagerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface ClientAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Image;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Article author (for article pages)
   */
  author?: (number | null) | Author;
  tags?: (number | PageTag)[] | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images".
 */
export interface Image {
  id: number;
  alt: string;
  /**
   * Attribution or copyright information
   */
  credit?: string | null;
  /**
   * Tags to categorize this image
   */
  tags?: (number | ImageTag)[] | null;
  fileMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-tags".
 */
export interface ImageTag {
  id: number;
  title: string;
  images?: {
    docs?: (number | Image)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * URL-friendly identifier (auto-generated from name)
   */
  slug: string;
  name: string;
  /**
   * Professional title (e.g., "Artist, writer and stylist")
   */
  title?: string | null;
  /**
   * Biography or description of the author
   */
  description?: string | null;
  /**
   * ISO 2-letter country code
   */
  countryCode?: string | null;
  /**
   * Years of meditation experience
   */
  yearsMeditating?: number | null;
  /**
   * Author profile image
   */
  image?: (number | null) | Image;
  articles?: {
    docs?: (number | Page)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-tags".
 */
export interface PageTag {
  id: number;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * URL-friendly identifier (auto-generated from title)
   */
  slug: string;
  /**
   * This localized title will be shown to public users
   */
  title: string;
  pages?: {
    docs?: (number | Page)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meditations".
 */
export interface Meditation {
  id: number;
  label: string;
  locale:
    | 'en'
    | 'es'
    | 'de'
    | 'it'
    | 'fr'
    | 'ru'
    | 'ro'
    | 'cs'
    | 'uk'
    | 'el'
    | 'hy'
    | 'pl'
    | 'pt-br'
    | 'fa'
    | 'bg'
    | 'tr';
  /**
   * This should be the name of the yogi who did the recording. We need this for dynamic followup audio clips.
   */
  narrator: number | Narrator;
  /**
   * Music with this tag will be offered to the seeker
   */
  musicTag?: (number | null) | MusicTag;
  fileMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  durationMinutes?: number | null;
  title?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  thumbnail?: (number | null) | Image;
  /**
   * Categorize this meditation for seekers to find it
   */
  tags?: (number | MeditationTag)[] | null;
  frames?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "narrators".
 */
export interface Narrator {
  id: number;
  name: string;
  gender: 'male' | 'female';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "music-tags".
 */
export interface MusicTag {
  id: number;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * URL-friendly identifier (auto-generated from title)
   */
  slug: string;
  /**
   * Localized title shown to public users
   */
  title: string;
  music?: {
    docs?: (number | Music)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "music".
 */
export interface Music {
  id: number;
  title: string;
  /**
   * The album this track belongs to
   */
  album: number | Album;
  tags?: (number | MusicTag)[] | null;
  fileMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums".
 */
export interface Album {
  id: number;
  title: string;
  artist: string;
  /**
   * Artist website or profile URL
   */
  artistUrl?: string | null;
  /**
   * Music tracks in this album
   */
  music?: {
    docs?: (number | Music)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meditation-tags".
 */
export interface MeditationTag {
  id: number;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * URL-friendly identifier (auto-generated from title)
   */
  slug: string;
  /**
   * Localized title shown to public users
   */
  title: string;
  /**
   * Tag color for UI theming (hex format)
   */
  color: string;
  meditations?: {
    docs?: (number | Meditation)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  title: string;
  /**
   * Story panels to introduce this lesson. First panel must be a Cover Panel.
   */
  panels: (
    | {
        title: string;
        quote: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cover';
      }
    | {
        /**
         * Video file for this panel.
         */
        video?: (number | null) | File;
        id?: string | null;
        blockName?: string | null;
        blockType: 'video';
      }
    | {
        title: string;
        text: string;
        image: number | Image;
        id?: string | null;
        blockName?: string | null;
        blockType: 'text';
      }
  )[];
  /**
   * Link to a related guided meditation that complements this lesson content.
   */
  meditation?: (number | null) | Meditation;
  /**
   * Audio introduction to this lesson.
   */
  introAudio?: (number | null) | File;
  introSubtitles?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  article?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  unit: 'Unit 1' | 'Unit 2' | 'Unit 3' | 'Unit 4';
  /**
   * This will determine the order of the path steps
   */
  step: number;
  icon?: (number | null) | Image;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Audio, video, and PDF files used by other collections. Orphaned files are automatically moved to trash and permanently deleted during monthly cleanup.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files".
 */
export interface File {
  id: number;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lectures".
 */
export interface Lecture {
  id: number;
  title: string;
  thumbnail: number | Image;
  videoUrl: string;
  subtitlesUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frames".
 */
export interface Frame {
  id: number;
  previewUrl?: string | null;
  imageSet: 'male' | 'female';
  category:
    | 'mooladhara'
    | 'swadhistan'
    | 'nabhi'
    | 'void'
    | 'anahat'
    | 'vishuddhi'
    | 'agnya'
    | 'sahasrara'
    | 'clearing'
    | 'kundalini'
    | 'meditate'
    | 'ready'
    | 'namaste';
  tags?:
    | (
        | 'anahat'
        | 'back'
        | 'bandhan'
        | 'both hands'
        | 'center'
        | 'channel'
        | 'earth'
        | 'ego'
        | 'feel'
        | 'ham ksham'
        | 'hamsa'
        | 'hand'
        | 'hands'
        | 'ida'
        | 'left'
        | 'lefthanded'
        | 'massage'
        | 'pingala'
        | 'raise'
        | 'right'
        | 'righthanded'
        | 'rising'
        | 'silent'
        | 'superego'
        | 'tapping'
      )[]
    | null;
  duration?: number | null;
  fileMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "managers".
 */
export interface Manager {
  id: number;
  name: string;
  currentProject?: ('' | 'wemeditate-web' | 'wemeditate-app' | 'sahaj-atlas') | null;
  /**
   * Set the manager's access level. Admin grants full access, Manager uses role-based permissions, Inactive blocks all access.
   */
  type: 'inactive' | 'manager' | 'admin';
  /**
   * Assign roles for each locale. Different roles can be assigned for different languages.
   */
  roles?: ('meditations-editor' | 'path-editor' | 'web-translator')[] | null;
  /**
   * Grant update access to specific documents. Useful for giving access to individual pages without broader permissions.
   */
  customResourceAccess?:
    | {
        relationTo: 'pages';
        value: number | Page;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  /**
   * Client organization or application name
   */
  name: string;
  /**
   * Purpose and usage notes for this client
   */
  notes?: string | null;
  /**
   * Assign API client roles. Roles apply to all locales.
   */
  roles?: ('wemeditate-web-client' | 'wemeditate-app-client' | 'sahaj-atlas-client')[] | null;
  /**
   * Users who can manage this client
   */
  managers: (number | Manager)[];
  /**
   * Primary user contact for this client
   */
  primaryContact: number | Manager;
  /**
   * What domains are associated with this client. Put each domain on a new line.
   */
  domains?: string | null;
  /**
   * Enable or disable API access for this client
   */
  active?: boolean | null;
  /**
   * Timestamp of last API key generation
   */
  keyGeneratedAt?: string | null;
  /**
   * API usage statistics
   */
  usageStats?: {
    /**
     * All-time request count
     */
    totalRequests?: number | null;
    /**
     * Today's request count
     */
    dailyRequests?: number | null;
    /**
     * Maximum historical request count
     */
    maxDailyRequests?: number | null;
    /**
     * Last API call timestamp
     */
    lastRequestAt?: string | null;
    /**
     * Indicates if daily limit exceeded (>1000 requests)
     */
    highUsageAlert?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'resetClientUsage' | 'trackClientUsage' | 'cleanupOrphanedMedia' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'resetClientUsage' | 'trackClientUsage' | 'cleanupOrphanedMedia' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'meditations';
        value: number | Meditation;
      } | null)
    | ({
        relationTo: 'music';
        value: number | Music;
      } | null)
    | ({
        relationTo: 'albums';
        value: number | Album;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'lectures';
        value: number | Lecture;
      } | null)
    | ({
        relationTo: 'frames';
        value: number | Frame;
      } | null)
    | ({
        relationTo: 'narrators';
        value: number | Narrator;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'images';
        value: number | Image;
      } | null)
    | ({
        relationTo: 'files';
        value: number | File;
      } | null)
    | ({
        relationTo: 'image-tags';
        value: number | ImageTag;
      } | null)
    | ({
        relationTo: 'meditation-tags';
        value: number | MeditationTag;
      } | null)
    | ({
        relationTo: 'music-tags';
        value: number | MusicTag;
      } | null)
    | ({
        relationTo: 'page-tags';
        value: number | PageTag;
      } | null)
    | ({
        relationTo: 'managers';
        value: number | Manager;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'managers';
        value: number | Manager;
      }
    | {
        relationTo: 'clients';
        value: number | Client;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'managers';
        value: number | Manager;
      }
    | {
        relationTo: 'clients';
        value: number | Client;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  generateSlug?: T;
  slug?: T;
  author?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meditations_select".
 */
export interface MeditationsSelect<T extends boolean = true> {
  label?: T;
  locale?: T;
  narrator?: T;
  musicTag?: T;
  fileMetadata?: T;
  durationMinutes?: T;
  title?: T;
  generateSlug?: T;
  slug?: T;
  thumbnail?: T;
  tags?: T;
  frames?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "music_select".
 */
export interface MusicSelect<T extends boolean = true> {
  title?: T;
  album?: T;
  tags?: T;
  fileMetadata?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums_select".
 */
export interface AlbumsSelect<T extends boolean = true> {
  title?: T;
  artist?: T;
  artistUrl?: T;
  music?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  title?: T;
  panels?:
    | T
    | {
        cover?:
          | T
          | {
              title?: T;
              quote?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              title?: T;
              text?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
      };
  meditation?: T;
  introAudio?: T;
  introSubtitles?: T;
  article?: T;
  unit?: T;
  step?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lectures_select".
 */
export interface LecturesSelect<T extends boolean = true> {
  title?: T;
  thumbnail?: T;
  videoUrl?: T;
  subtitlesUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frames_select".
 */
export interface FramesSelect<T extends boolean = true> {
  previewUrl?: T;
  imageSet?: T;
  category?: T;
  tags?: T;
  duration?: T;
  fileMetadata?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "narrators_select".
 */
export interface NarratorsSelect<T extends boolean = true> {
  name?: T;
  gender?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  generateSlug?: T;
  slug?: T;
  name?: T;
  title?: T;
  description?: T;
  countryCode?: T;
  yearsMeditating?: T;
  image?: T;
  articles?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images_select".
 */
export interface ImagesSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  tags?: T;
  fileMetadata?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files_select".
 */
export interface FilesSelect<T extends boolean = true> {
  createdAt?: T;
  updatedAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-tags_select".
 */
export interface ImageTagsSelect<T extends boolean = true> {
  title?: T;
  images?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meditation-tags_select".
 */
export interface MeditationTagsSelect<T extends boolean = true> {
  generateSlug?: T;
  slug?: T;
  title?: T;
  color?: T;
  meditations?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "music-tags_select".
 */
export interface MusicTagsSelect<T extends boolean = true> {
  generateSlug?: T;
  slug?: T;
  title?: T;
  music?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-tags_select".
 */
export interface PageTagsSelect<T extends boolean = true> {
  generateSlug?: T;
  slug?: T;
  title?: T;
  pages?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "managers_select".
 */
export interface ManagersSelect<T extends boolean = true> {
  name?: T;
  currentProject?: T;
  type?: T;
  roles?: T;
  customResourceAccess?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  notes?: T;
  roles?: T;
  managers?: T;
  primaryContact?: T;
  domains?: T;
  active?: T;
  keyGeneratedAt?: T;
  usageStats?:
    | T
    | {
        totalRequests?: T;
        dailyRequests?: T;
        maxDailyRequests?: T;
        lastRequestAt?: T;
        highUsageAlert?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "we-meditate-web-settings".
 */
export interface WeMeditateWebSetting {
  id: number;
  /**
   * Select the page content for the home page
   */
  homePage: number | Page;
  /**
   * Select 3-7 pages to feature in the website menu. Drag to reorder.
   */
  featuredPages: (number | Page)[];
  /**
   * Select 3-5 pages to display in the website footer
   */
  footerPages: (number | Page)[];
  musicPage: number | Page;
  /**
   * Select 3-5 music tags to display on the Music page
   */
  musicPageTags: (number | MusicTag)[];
  subtleSystemPage: number | Page;
  left: number | Page;
  right: number | Page;
  center: number | Page;
  mooladhara: number | Page;
  kundalini: number | Page;
  swadhistan: number | Page;
  nabhi: number | Page;
  void: number | Page;
  anahat: number | Page;
  vishuddhi: number | Page;
  agnya: number | Page;
  sahasrara: number | Page;
  techniquesPage: number | Page;
  /**
   * Select the page tag that represents all technique pages
   */
  techniquePageTag: number | PageTag;
  inspirationPage: number | Page;
  /**
   * Select 3-5 page tags to display on the Inspiration page
   */
  inspirationPageTags: (number | PageTag)[];
  classesPage: number | Page;
  /**
   * Select the page for live meditation classes
   */
  liveMeditationsPage: number | Page;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "we-meditate-app-settings".
 */
export interface WeMeditateAppSetting {
  id: number;
  /**
   * Current mobile app version
   */
  appVersion?: string | null;
  /**
   * Select up to 10 meditations to feature in the mobile app
   */
  featuredMeditations?: (number | Meditation)[] | null;
  /**
   * Select up to 10 lessons to feature in the mobile app
   */
  featuredLessons?: (number | Lesson)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sahaj-atlas-settings".
 */
export interface SahajAtlasSetting {
  id: number;
  /**
   * Current Sahaj Atlas version
   */
  atlasVersion?: string | null;
  defaultMapCenter: {
    latitude: number;
    longitude: number;
  };
  defaultZoomLevel?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "we-meditate-web-settings_select".
 */
export interface WeMeditateWebSettingsSelect<T extends boolean = true> {
  homePage?: T;
  featuredPages?: T;
  footerPages?: T;
  musicPage?: T;
  musicPageTags?: T;
  subtleSystemPage?: T;
  left?: T;
  right?: T;
  center?: T;
  mooladhara?: T;
  kundalini?: T;
  swadhistan?: T;
  nabhi?: T;
  void?: T;
  anahat?: T;
  vishuddhi?: T;
  agnya?: T;
  sahasrara?: T;
  techniquesPage?: T;
  techniquePageTag?: T;
  inspirationPage?: T;
  inspirationPageTags?: T;
  classesPage?: T;
  liveMeditationsPage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "we-meditate-app-settings_select".
 */
export interface WeMeditateAppSettingsSelect<T extends boolean = true> {
  appVersion?: T;
  featuredMeditations?: T;
  featuredLessons?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sahaj-atlas-settings_select".
 */
export interface SahajAtlasSettingsSelect<T extends boolean = true> {
  atlasVersion?: T;
  defaultMapCenter?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  defaultZoomLevel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskResetClientUsage".
 */
export interface TaskResetClientUsage {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskTrackClientUsage".
 */
export interface TaskTrackClientUsage {
  input: {
    clientId: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCleanupOrphanedMedia".
 */
export interface TaskCleanupOrphanedMedia {
  input?: unknown;
  output: {
    permanentlyDeletedFiles: number;
    permanentlyDeletedImages: number;
    trashedFiles: number;
    trashedImages: number;
    skippedImages: number;
    errors: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'meditations';
          value: number | Meditation;
        } | null);
    global?: string | null;
    user?: (number | null) | Manager;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}